### ISSUE TITLE
Computing height of tree

### ISSUE THREAD

**Issue by meenakshisl** [swaminathanj/DSA#4]
https://github.com/swaminathanj/DSA/blob/f2db8a2ae49c61d0ab5764aed3ea66fbdb245300/src/AVLNode.java#L225-L227

Shouldn't the last line supposed to be left.height() + right.height() ? Since right is calculated as 
-1*(right.height() + 1)  ?

**Comment by RevathiChundi** [comment]
NO

**Comment by ChamKrish** [comment]
No because **-1\*(right.height() + 1)** is calculated for *nodes having only right* and **left.height() - right.height()** is calculated for *nodes having both left and right*.
